//! Semantic-search provider configuration.
//!
//! Semantic search is re-ranking via TypeSafe's Jev model (see [`crate::jev`]):
//! a fast BM25/FTS5 shortlist is scored one-candidate-at-a-time by Jev, then
//! sorted by the returned `noul` probability. No embeddings are stored, so
//! this module holds only the provider selection and its credentials.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Provider {
    /// TypeSafe's Jev model. Cloud re-ranking; requires an API key.
    Jev,
    /// Semantic search turned off — the palette falls back to fuzzy matching.
    Disabled,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmbedConfig {
    pub provider: Provider,
    #[serde(default = "default_typesafe_model")]
    pub typesafe_model: String,
    pub typesafe_api_key: String,
    /// Independent of semantic search — drives the one-line intent labels
    /// generated by Claude Haiku in the background.
    pub anthropic_api_key: String,
}

fn default_typesafe_model() -> String {
    "jev-latest".into()
}

impl Default for EmbedConfig {
    fn default() -> Self {
        Self {
            provider: Provider::Jev,
            typesafe_model: default_typesafe_model(),
            typesafe_api_key: String::new(),
            anthropic_api_key: String::new(),
        }
    }
}

impl EmbedConfig {
    pub fn is_active(&self) -> bool {
        match self.provider {
            Provider::Disabled => false,
            Provider::Jev => !self.typesafe_api_key.trim().is_empty(),
        }
    }
}
