//! Semantic-search provider configuration.
//!
//! - `Local` (default): bundled ONNX embeddings (see [`crate::local_embed`]),
//!   fused with a BM25 shortlist via reciprocal rank fusion. Offline.
//! - `Jev`: opt-in TypeSafe re-ranking of the BM25 shortlist (see
//!   [`crate::jev`]). Needs the user's own API key; nothing is stored.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Provider {
    /// Bundled ONNX embedding model running entirely on the user's machine.
    Local,
    /// TypeSafe's Jev model. Cloud re-ranking; requires an API key.
    Jev,
    /// Semantic search turned off — the palette falls back to fuzzy matching.
    Disabled,
}

/// Whether we are embedding a stored document or an active query.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EmbedTask {
    Document,
    Query,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmbedConfig {
    pub provider: Provider,
    #[serde(default = "default_local_model")]
    pub local_model: String,
    #[serde(default = "default_typesafe_model")]
    pub typesafe_model: String,
    #[serde(default)]
    pub typesafe_api_key: String,
    /// Independent of semantic search — drives the one-line intent labels
    /// generated by Claude Haiku in the background.
    #[serde(default)]
    pub anthropic_api_key: String,
}

fn default_local_model() -> String {
    "bge-small-en-v1.5".into()
}

fn default_typesafe_model() -> String {
    "jev-latest".into()
}

impl Default for EmbedConfig {
    fn default() -> Self {
        Self {
            provider: Provider::Local,
            local_model: default_local_model(),
            typesafe_model: default_typesafe_model(),
            typesafe_api_key: String::new(),
            anthropic_api_key: String::new(),
        }
    }
}

impl EmbedConfig {
    pub fn is_active(&self) -> bool {
        match self.provider {
            Provider::Disabled => false,
            // Local is always active — the model loads (or downloads) on demand.
            Provider::Local => true,
            Provider::Jev => !self.typesafe_api_key.trim().is_empty(),
        }
    }

    /// Identifies which vectors are valid. Bump the suffix whenever the
    /// document input format changes so old embeddings are re-generated.
    /// v4: labels/content edited while embeddings were dropped left v3 stale.
    pub fn model_id(&self) -> String {
        format!("local:{}:v4", self.local_model)
    }
}

/// L2-normalize so cosine = dot product.
pub fn normalize(mut v: Vec<f32>) -> Vec<f32> {
    let norm: f32 = v.iter().map(|x| x * x).sum::<f32>().sqrt();
    if norm > 0.0 {
        for x in &mut v {
            *x /= norm;
        }
    }
    v
}

pub fn to_bytes(v: &[f32]) -> Vec<u8> {
    v.iter().flat_map(|x| x.to_le_bytes()).collect()
}

pub fn from_bytes(b: &[u8]) -> Vec<f32> {
    b.chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

/// Dot product of two L2-normalized vectors = cosine similarity.
pub fn cosine(a: &[f32], b: &[f32]) -> f32 {
    a.iter().zip(b).map(|(x, y)| x * y).sum()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn older_stored_configs_still_parse() {
        let jev_era: EmbedConfig = serde_json::from_str(
            r#"{"provider":"jev","typesafe_model":"jev-latest","typesafe_api_key":"","anthropic_api_key":"sk-ant"}"#,
        )
        .unwrap();
        assert_eq!(jev_era.local_model, "bge-small-en-v1.5");
        assert_eq!(jev_era.anthropic_api_key, "sk-ant");

        let pre_jev: EmbedConfig = serde_json::from_str(
            r#"{"provider":"local","local_model":"all-minilm-l6-v2","openai_api_key":"","anthropic_api_key":"sk-ant"}"#,
        )
        .unwrap();
        assert_eq!(pre_jev.provider, Provider::Local);
        assert_eq!(pre_jev.typesafe_model, "jev-latest");
        assert!(pre_jev.is_active());
    }
}
