//! Semantic search: local embeddings + an optional typed-decision re-ranker.
//!
//! Stage 1 (always, fully local): every clip is embedded once with
//! EmbeddingGemma-300M (4-bit ONNX, ~200 MB, downloaded on first use). A
//! search embeds the query and ranks every clip by cosine similarity. This
//! finds paraphrases BM25 can't ("where dad gets his mail" -> an address).
//!
//! Stage 2 (optional): the top of that list is handed to a System One model
//! — TypeSafe's Jev in the cloud, or Laya running locally on MLX — as one
//! Choice question, and re-sorted by its probabilities (see [`crate::jev`]).
//! Both providers speak the same `/v1/systemone` contract, so the logic is
//! identical; only the endpoint differs.
//!
//! Numbers behind these choices live in `examples/bench/` (eval report).

use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Mutex, OnceLock};

use fastembed::{EmbeddingModel, TextEmbedding, TextInitOptions};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Provider {
    /// Local embeddings only. No network, no key.
    Local,
    /// Local embeddings, then TypeSafe's Jev re-ranks the shortlist (cloud).
    Jev,
    /// Local embeddings, then Laya re-ranks the shortlist via a local
    /// TypeSafe-compatible server (`scripts/laya_server.py`).
    Laya,
    /// Semantic search turned off — the palette falls back to fuzzy matching.
    Disabled,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmbedConfig {
    pub provider: Provider,
    #[serde(default = "default_typesafe_model")]
    pub typesafe_model: String,
    #[serde(default)]
    pub typesafe_api_key: String,
    #[serde(default = "default_laya_url")]
    pub laya_url: String,
    /// Independent of semantic search — drives the one-line intent labels
    /// generated by Claude Haiku in the background.
    #[serde(default)]
    pub anthropic_api_key: String,
}

fn default_typesafe_model() -> String {
    "jev-latest".into()
}

pub fn default_laya_url() -> String {
    "http://127.0.0.1:8765/v1/systemone".into()
}

impl Default for EmbedConfig {
    fn default() -> Self {
        Self {
            provider: Provider::Local,
            typesafe_model: default_typesafe_model(),
            typesafe_api_key: String::new(),
            laya_url: default_laya_url(),
            anthropic_api_key: String::new(),
        }
    }
}

/// Where a re-rank request goes, and how far to trust it. `api_key` is
/// empty for the local Laya server.
pub struct Reranker {
    pub url: String,
    pub api_key: String,
    pub model: String,
    /// Shortlist size sent for re-ranking.
    pub pool: usize,
    /// Blend of re-ranker vs embedding score (1.0 = re-ranker decides).
    /// Tuned on the eval set: Jev alone beats any blend; Laya is best as an
    /// equal partner to the embedding score (0.79 -> 0.83 top-1).
    pub weight: f32,
}

impl EmbedConfig {
    pub fn is_active(&self) -> bool {
        self.provider != Provider::Disabled
    }

    /// The configured stage-2 re-ranker, if any. Jev without a key degrades
    /// to local-only ranking rather than failing searches.
    pub fn reranker(&self) -> Option<Reranker> {
        match self.provider {
            Provider::Jev if !self.typesafe_api_key.trim().is_empty() => Some(Reranker {
                url: crate::jev::ENDPOINT.into(),
                api_key: self.typesafe_api_key.trim().into(),
                model: self.typesafe_model.clone(),
                pool: 50, // latency is the round-trip, flat in pool size
                weight: 1.0,
            }),
            Provider::Laya => Some(Reranker {
                url: self.laya_url.trim().into(),
                api_key: String::new(),
                model: "laya".into(),
                pool: 20, // local compute grows with the pool
                weight: 0.5,
            }),
            _ => None,
        }
    }
}

// ---------------------------------------------------------------------------
// Local embedding model
// ---------------------------------------------------------------------------

/// Stored next to each vector; bump when the model or document text changes
/// so the embed queue re-embeds everything.
pub const MODEL_ID: &str = "embeddinggemma-300m-q4/v2";

/// EmbeddingGemma's retrieval prompts (from the model card).
const QUERY_PROMPT: &str = "task: search result | query: ";
const DOC_PROMPT: &str = "title: none | text: ";

/// Characters of a clip we embed. The head carries the meaning; long log
/// dumps would only add latency.
const MAX_DOC_CHARS: usize = 500;

static CACHE_DIR: OnceLock<PathBuf> = OnceLock::new();
static MODEL: Mutex<Option<TextEmbedding>> = Mutex::new(None);
/// Set once the model is loaded; until then queries don't wait on the
/// (first-run: ~200 MB download) load and search answers from BM25.
static READY: AtomicBool = AtomicBool::new(false);
static LOADING: AtomicBool = AtomicBool::new(false);

/// Set where model files are downloaded. Call once at startup.
pub fn init(cache_dir: PathBuf) {
    let _ = CACHE_DIR.set(cache_dir);
}

fn with_model<R>(f: impl FnOnce(&mut TextEmbedding) -> Result<R, String>) -> Result<R, String> {
    let mut guard = MODEL.lock().map_err(|e| e.to_string())?;
    if guard.is_none() {
        let dir = CACHE_DIR
            .get()
            .cloned()
            .unwrap_or_else(|| PathBuf::from(".fastembed_cache"));
        std::fs::create_dir_all(&dir).map_err(|e| format!("model dir: {e}"))?;
        let opts = TextInitOptions::new(EmbeddingModel::EmbeddingGemma300MQ4)
            .with_cache_dir(dir)
            .with_show_download_progress(false);
        *guard = Some(TextEmbedding::try_new(opts).map_err(|e| format!("embedding model: {e}"))?);
        READY.store(true, Ordering::Release);
    }
    f(guard.as_mut().expect("initialised above"))
}

/// Embed clip texts (from [`doc_text`]). Blocking — call off the async runtime.
pub fn embed_docs(texts: &[String]) -> Result<Vec<Vec<f32>>, String> {
    let prompted: Vec<String> = texts.iter().map(|t| format!("{DOC_PROMPT}{t}")).collect();
    with_model(|m| m.embed(&prompted, Some(8)).map_err(|e| e.to_string()))
        .map(|vs| vs.into_iter().map(normalize).collect())
}

/// Embed a search query. Blocking — call off the async runtime. Returns an
/// error right away (and starts loading in the background) if the model
/// isn't ready yet.
pub fn embed_query(text: &str) -> Result<Vec<f32>, String> {
    if !READY.load(Ordering::Acquire) {
        if !LOADING.swap(true, Ordering::AcqRel) {
            std::thread::spawn(|| {
                if let Err(e) = with_model(|_| Ok(())) {
                    eprintln!("[embed] {e}");
                }
                LOADING.store(false, Ordering::Release);
            });
        }
        return Err("embedding model is still loading".into());
    }
    with_model(|m| {
        m.embed(&[format!("{QUERY_PROMPT}{text}")], None)
            .map_err(|e| e.to_string())
    })?
    .pop()
    .map(normalize)
    .ok_or_else(|| "empty embedding".into())
}

/// The text a clip is embedded as: `[category] label / body / (from app)`.
/// Category and source each lifted top-1 accuracy ~2 pts on the eval set
/// ("the link from slack"); colour swatches also get their nearest names.
pub fn doc_text(
    category: &str,
    label: Option<&str>,
    content: &str,
    source: Option<&str>,
) -> String {
    let mut body: String = content.trim().chars().take(MAX_DOC_CHARS).collect();
    if category == "color" {
        let names = crate::color_names::enrich_color_text(&body);
        if !names.is_empty() {
            body = format!("{body} {names}");
        }
    }
    let mut out = format!("[{category}] ");
    if let Some(l) = label.map(str::trim).filter(|l| !l.is_empty()) {
        out.push_str(l);
        out.push('\n');
    }
    out.push_str(&body);
    if let Some(src) = source.map(str::trim).filter(|s| !s.is_empty()) {
        out.push_str(&format!("\n(from {src})"));
    }
    out
}

// ---------------------------------------------------------------------------
// In-memory vector index
// ---------------------------------------------------------------------------

/// Every stored vector, flat, so a search is one dot-product pass instead of a
/// 3 KB-per-row SQLite read (20k clips: ~5 ms vs >100 ms). Loaded from the DB
/// on first search; the embed queue upserts after that. Deleted clips may
/// linger until restart — `search` drops them when it loads rows.
struct Index {
    loaded: bool,
    pos: std::collections::HashMap<i64, usize>,
    meta: Vec<(i64, i64, String)>, // (id, created_at, category)
    vecs: Vec<f32>,
}

static INDEX: std::sync::LazyLock<Mutex<Index>> = std::sync::LazyLock::new(|| {
    Mutex::new(Index {
        loaded: false,
        pos: Default::default(),
        meta: Vec::new(),
        vecs: Vec::new(),
    })
});

impl Index {
    fn upsert(&mut self, id: i64, created: i64, category: String, v: &[f32]) {
        if v.len() != DIM {
            return;
        }
        match self.pos.get(&id) {
            Some(&p) => {
                self.meta[p] = (id, created, category);
                self.vecs[p * DIM..(p + 1) * DIM].copy_from_slice(v);
            }
            None => {
                self.pos.insert(id, self.meta.len());
                self.meta.push((id, created, category));
                self.vecs.extend_from_slice(v);
            }
        }
    }
}

const DIM: usize = 768;

/// Record a freshly stored vector (no-op until the index is first loaded).
pub fn index_upsert(id: i64, created: i64, category: &str, v: &[f32]) {
    if let Ok(mut ix) = INDEX.lock() {
        if ix.loaded {
            ix.upsert(id, created, category.to_string(), v);
        }
    }
}

/// Cosine of `q` against every indexed clip created in `[from, to]`.
/// Returns `(id, cosine, category, created_at)`.
pub fn scan(
    conn: &rusqlite::Connection,
    q: &[f32],
    from: i64,
    to: i64,
) -> Result<Vec<(i64, f32, String, i64)>, String> {
    let mut ix = INDEX.lock().map_err(|e| e.to_string())?;
    if !ix.loaded {
        let mut stmt = conn
            .prepare(
                "SELECT id, created_at, category, embedding FROM items
                 WHERE deleted = 0 AND embedding_model = ?1",
            )
            .map_err(|e| e.to_string())?;
        let mut rows = stmt.query([MODEL_ID]).map_err(|e| e.to_string())?;
        while let Some(r) = rows.next().map_err(|e| e.to_string())? {
            let blob = r
                .get_ref(3)
                .map_err(|e| e.to_string())?
                .as_blob()
                .map_err(|e| e.to_string())?;
            let v: Vec<f32> = blob
                .chunks_exact(4)
                .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
                .collect();
            let (id, created, cat) = (
                r.get(0).map_err(|e| e.to_string())?,
                r.get(1).map_err(|e| e.to_string())?,
                r.get(2).map_err(|e| e.to_string())?,
            );
            ix.upsert(id, created, cat, &v);
        }
        ix.loaded = true;
    }
    Ok(ix
        .meta
        .iter()
        .zip(ix.vecs.chunks_exact(DIM))
        .filter(|((_, created, _), _)| (from..=to).contains(created))
        .map(|((id, created, cat), v)| {
            (
                *id,
                q.iter().zip(v).map(|(a, b)| a * b).sum(),
                cat.clone(),
                *created,
            )
        })
        .collect())
}

pub fn normalize(mut v: Vec<f32>) -> Vec<f32> {
    let n = v.iter().map(|x| x * x).sum::<f32>().sqrt();
    if n > 0.0 {
        v.iter_mut().for_each(|x| *x /= n);
    }
    v
}

pub fn to_bytes(v: &[f32]) -> Vec<u8> {
    v.iter().flat_map(|x| x.to_le_bytes()).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn index_upsert_replaces_in_place() {
        let mut ix = Index {
            loaded: true,
            pos: Default::default(),
            meta: vec![],
            vecs: vec![],
        };
        ix.upsert(7, 1, "text".into(), &vec![0.0; DIM]);
        ix.upsert(7, 2, "code".into(), &vec![1.0; DIM]);
        assert_eq!(ix.meta, vec![(7, 2, "code".to_string())]);
        assert_eq!(ix.vecs.len(), DIM);
        assert_eq!(ix.vecs[0], 1.0);
    }

    #[test]
    fn legacy_jev_config_without_new_fields_still_loads() {
        let cfg: EmbedConfig = serde_json::from_str(
            r#"{"provider":"jev","typesafe_model":"jev-latest","typesafe_api_key":"","anthropic_api_key":""}"#,
        )
        .unwrap();
        assert!(cfg.is_active());
        assert!(
            cfg.reranker().is_none(),
            "Jev without a key must fall back to local ranking"
        );
        assert_eq!(cfg.laya_url, default_laya_url());
    }
}
